#' Common sequences bar plot
#'
#' Creates an UpSet plot showing the number of intersecting sequences
#' across multiple repertoire_ids using the UpSetR package. This
#' function is useful when more than 3 repertoire_ids are being compared.
#'
#' @param amino_table A tibble of productive amino acid sequences
#' generated by LymphoSeq2 function productiveSeq where the aggregate parameter
#' was set to "junction_aa".
#' @param repertoire_ids The names of two or more repertoire_ids in the
#' amino_table list whose intersections will shown.
#' @param color_sample The name of a single repertoire_id in the amino_table
#' whose sequences will be colored in all repertoire_ids that they appear in.
#' @param color_intersection The names of two or more repertoire_ids in the
#' amino_table intersections will be colored.
#' @param color A character vector of a color name that will be used highlight
#' a selected repertoire_id or multiple repertoire_id intersections.
#' @param labels A character vector indicating whether the number of
#' intersecting sequences should be shown on the tops of the bars.Options
#' include "yes" or "no".
#' @return Returns an UpSetR plot showing the number of
#' intersecting sequences across multiple repertoire_ids.
#' @seealso [LymphoSeq2::productiveSeq()], [LymphoSeq2::commonSeqs()],
#' [LymphoSeq2::commonSeqsVenn()], [LymphoSeq2::commonSeqsPlot()]
#' @examples
#' \dontrun{
#' file_path <- system.file("extdata", "TCRB_sequencing",
#'  package = "LymphoSeq2")
#' study_table <- LymphoSeq2::readImmunoSeq(path = file_path, threads = 1)
#' study_table <- LymphoSeq2::topSeqs(study_table, top = 100)
#' amino_table <- LymphoSeq2::productiveSeq(study_table,
#'  aggregate = "junction_aa")
#' LymphoSeq2::commonSeqsBar(amino_table, repertoire_ids = c(
#'   "TRB_CD4_949", "TRB_CD8_949",
#'   "TRB_Unsorted_949", "TRB_Unsorted_1320"
#' ), color_sample = "TRB_CD8_949")
#' }
#' @export
commonSeqsBar <- function(amino_table, repertoire_ids, color_sample = NULL,
                          color_intersection = NULL, color = "#377eb8",
                          labels = "no") {

  # Check if UpSetR is available
  if (!requireNamespace("UpSetR", quietly = TRUE)) {
    stop("Package 'UpSetR' is required for this function. ",
         "Please install it with: install.packages('UpSetR')",
         call. = FALSE)
  }

  # Create list of sequences for each repertoire
  seq_list <- lapply(repertoire_ids, function(id) {
    amino_table |>
      dplyr::filter(repertoire_id == id) |>
      dplyr::pull(junction_aa)
  })
  names(seq_list) <- repertoire_ids

  # Determine which sets/intersections to highlight
  queries <- list()
  if (!is.null(color_sample)) {
    # Highlight all intersections containing the specified sample
    queries <- list(
      list(
        query = UpSetR::intersects,
        params = list(color_sample),
        color = color,
        active = TRUE,
        query.name = color_sample
      )
    )
  } else if (!is.null(color_intersection)) {
    # Highlight specific intersection
    queries <- list(
      list(
        query = UpSetR::intersects,
        params = as.list(color_intersection),
        color = color,
        active = TRUE,
        query.name = paste(color_intersection, collapse = " & ")
      )
    )
  }

  # Create UpSet plot
  if (length(queries) > 0) {
    p <- UpSetR::upset(
      UpSetR::fromList(seq_list),
      nsets = length(repertoire_ids),
      order.by = "freq",
      text.scale = c(1.3, 1.3, 1, 1, 1.5, 1.2),
      mainbar.y.label = "Number of intersecting sequences",
      sets.bar.color = "gray30",
      queries = queries,
      query.legend = "top"
    )
  } else {
    p <- UpSetR::upset(
      UpSetR::fromList(seq_list),
      nsets = length(repertoire_ids),
      order.by = "freq",
      text.scale = c(1.3, 1.3, 1, 1, 1.5, 1.2),
      mainbar.y.label = "Number of intersecting sequences",
      sets.bar.color = "gray30"
    )
  }

  return(p)
}
