#' Common sequences plot
#' 
#' Creates a scatter plot of just the sequences in common between two samples.
#' 
#' @param sample1 A name of a repertoire_id in a list of data frames generated by the 
#' LymphoSeq function productiveSeq.
#' @param sample2 A name of a repertoire_id in a list of data frames generated by the 
#' LymphoSeq function productiveSeq.
#' @param productive_aa A tibble of productive amino acid sequences 
#' produced by the LymphoSeq function productiveSeq containing the 
#' samples to be compared.
#' @param show A character vector specifying whether only the common sequences 
#' should be shown or all sequences.  Available options are "common" or "all".
#' @return Returns a frequency scatter plot of two samples showing only the 
#' shared sequences.
#' @details The plot is made using the package ggplot2 and can be reformatted
#' using ggplot2 functions.  See examples below.
#' @seealso An excellent resource for examples on how to reformat a ggplot can 
#' be found in the R Graphics Cookbook online (\url{http://www.cookbook-r.com/Graphs/}).
#' @examples
#' file.path <- system.file("extdata", "TCRB_sequencing", package = "LymphoSeq")
#' 
#' study_table <- readImmunoSeq(path = file.path)
#' 
#' productive_aa <- productiveSeq(study_table = study_table, aggregate = "junction_aa")
#' 
#' commonSeqsPlot("TRB_Unsorted_32", "TRB_Unsorted_83", 
#'    productive.aa = productive.aa)
#' 
#' # Change the X and Y axises to log-10 scale
#' commonSeqsPlot("TRB_Unsorted_32", "TRB_Unsorted_83", 
#'    productive.aa = productive.aa) +
#'    ggplot2::scale_x_log10() + 
#'    ggplot2::scale_y_log10() + 
#'    ggplot2::annotation_logticks(sides = "bl")
#' @export
#' @import ggplot2
#' @import tidyverse
commonSeqsPlot <- function(sample1, sample2, productive_aa, show = "common") {
    # Check if tibble is contains unproductive sequences
    if (show == "common") {
        common <- commonSeqs(samples = c(sample1, sample2), 
                             productive_aa = productive_aa)
        plot <- ggplot(data = common, 
                       aes_string(x = names(common)[2], 
                                  y = names(common)[3], 
                                  label = "junction_aa")) + 
                geom_point() +
                theme_minimal() + 
                labs(x = paste(sample1, "frequency (%)"), 
                     y = paste(sample2, "frequency (%)"))
    }
    if (show == "all") {
        stable1 <- productive_aa %>% 
                   filter(repertoire_id == sample1)
        stable2 <- productive_aa %>% 
                   filter(repertoire_id == sample2)
        all <- full_join(stable1, stable2, by = "junction_aa") %>% 
               mutate_all(~replace(., is.na(.), 0))
        all <- all %>% 
               recode(duplicate_frequency.x = sample1, 
                      duplicate_frequency.y = sample2)
        plot <- ggplot2::ggplot(data = all, 
                                aes_string(x = sample1, 
                                           y = sample2, 
                                           label = "junction_aa")) + 
                geom_point() +
                theme_minimal() + 
                labs(x = paste(sample1, "frequency (%)"), y = paste(sample2, "frequency (%)"))
    }
    return(plot)
}