#' Common sequences bar plot
#'
#' Creates an UpSet-style bar plot showing the number of intersecting sequences
#' across multiple repertoire_ids using native ggplot2 implementation. This
#' function is useful when more than 3 repertoire_ids are being compared.
#'
#' @param amino_table A tibble of productive amino acid sequences
#' generated by LymphoSeq2 function productiveSeq where the aggregate parameter
#' was set to "junction_aa".
#' @param repertoire_ids The names of two or more repertoire_ids in the
#' amino_table list whose intersections will shown.
#' @param color_sample The name of a single repertoire_id in the amino_table
#' whose sequences will be colored in all repertoire_ids that they appear in.
#' @param color_intersection The names of two or more repertoire_ids in the
#' amino_table intersections will be colored.
#' @param color A character vector of a color name that will be used highlight
#' a selected repertoire_id or multiple repertoire_id intersections.
#' @param labels A character vector indicating whether the number of
#' intersecting sequences should be shown on the tops of the bars.Options
#' include "yes" or "no".
#' @return Returns a ggplot2 UpSet-style bar plot showing the number of
#' intersecting sequences across multiple repertoire_ids.
#' @seealso [LymphoSeq2::productiveSeq()], [LymphoSeq2::commonSeqs()],
#' [LymphoSeq2::commonSeqsVenn()], [LymphoSeq2::commonSeqsPlot()]
#' @examples
#' file_path <- system.file("extdata", "TCRB_sequencing",
#'  package = "LymphoSeq2")
#' study_table <- LymphoSeq2::readImmunoSeq(path = file_path, threads = 1)
#' study_table <- LymphoSeq2::topSeqs(study_table, top = 100)
#' amino_table <- LymphoSeq2::productiveSeq(study_table,
#'  aggregate = "junction_aa")
#' LymphoSeq2::commonSeqsBar(amino_table, repertoire_ids = c(
#'   "TRB_CD4_949", "TRB_CD8_949",
#'   "TRB_Unsorted_949", "TRB_Unsorted_1320"
#' ), color_sample = "TRB_CD8_949")
#' @export
commonSeqsBar <- function(amino_table, repertoire_ids, color_sample = NULL,
                          color_intersection = NULL, color = "#377eb8",
                          labels = "no") {
  # Get unique sequences and create binary matrix
  unique_seqs <- LymphoSeq2::uniqueSeqs(productive_table = amino_table) |>
    dplyr::pull(junction_aa)

  sequence_matrix <- LymphoSeq2::seqMatrix(
    amino_table = amino_table,
    sequences = unique_seqs
  )

  junction_aa <- sequence_matrix |>
    dplyr::pull(junction_aa)

  sequence_matrix <- sequence_matrix |>
    dplyr::select(-junction_aa) |>
    base::as.matrix()

  # Convert to binary (0/1)
  sequence_matrix[sequence_matrix > 0] <- 1

  # Create native UpSet plot
  upset_data <- prepare_upset_data(sequence_matrix, repertoire_ids, junction_aa)

  # Determine which bars to highlight
  highlight_sets <- NULL
  if (!is.null(color_sample)) {
    seq_list <- amino_table |>
      dplyr::filter(repertoire_id == color_sample) |>
      dplyr::pull(junction_aa)
    highlight_sets <- upset_data$intersections[
      upset_data$intersections$junction_aa %in% seq_list, "intersection_id"
    ]
  } else if (!is.null(color_intersection)) {
    highlight_sets <- upset_data$intersections[
      upset_data$intersections$combination == paste(sort(color_intersection), collapse = "&"),
      "intersection_id"
    ]
  }

  # Create the plot
  p <- plot_upset_native(
    upset_data = upset_data,
    repertoire_ids = repertoire_ids,
    highlight_sets = highlight_sets,
    highlight_color = color,
    show_numbers = (labels == "yes")
  )

  return(p)
}

#' Prepare data for UpSet plot
#'
#' @param binary_matrix Binary matrix (rows = sequences, cols = sets)
#' @param set_names Names of sets
#' @param sequence_ids Sequence identifiers
#' @return List with intersection data
#' @keywords internal
prepare_upset_data <- function(binary_matrix, set_names, sequence_ids) {
  # Create combination string for each sequence
  n_seqs <- nrow(binary_matrix)
  combinations <- character(n_seqs)

  for (i in 1:n_seqs) {
    present_sets <- set_names[binary_matrix[i, ] == 1]
    if (length(present_sets) > 0) {
      combinations[i] <- paste(sort(present_sets), collapse = "&")
    } else {
      combinations[i] <- "None"
    }
  }

  # Count each combination
  combo_counts <- table(combinations)
  combo_df <- data.frame(
    combination = names(combo_counts),
    count = as.numeric(combo_counts),
    stringsAsFactors = FALSE
  )

  # Sort by count descending
  combo_df <- combo_df[order(-combo_df$count), ]
  combo_df$intersection_id <- 1:nrow(combo_df)

  # Create matrix for connection dots
  connection_matrix <- matrix(0, nrow = nrow(combo_df), ncol = length(set_names))
  colnames(connection_matrix) <- set_names

  for (i in 1:nrow(combo_df)) {
    sets_in_combo <- strsplit(combo_df$combination[i], "&")[[1]]
    connection_matrix[i, sets_in_combo] <- 1
  }

  # Map sequences to intersection IDs
  seq_to_intersection <- data.frame(
    junction_aa = sequence_ids,
    combination = combinations,
    stringsAsFactors = FALSE
  )
  seq_to_intersection <- merge(seq_to_intersection,
                                 combo_df[, c("combination", "intersection_id")],
                                 by = "combination")

  # Calculate set sizes
  set_sizes <- colSums(binary_matrix)

  return(list(
    intersections = combo_df,
    connections = connection_matrix,
    set_sizes = set_sizes,
    seq_mapping = seq_to_intersection
  ))
}

#' Plot native UpSet-style visualization
#'
#' @param upset_data List from prepare_upset_data
#' @param repertoire_ids Set names
#' @param highlight_sets Intersection IDs to highlight
#' @param highlight_color Color for highlighted bars
#' @param show_numbers Whether to show counts on bars
#' @return ggplot object
#' @keywords internal
plot_upset_native <- function(upset_data, repertoire_ids,
                               highlight_sets = NULL,
                               highlight_color = "#377eb8",
                               show_numbers = FALSE) {

  intersections <- upset_data$intersections
  connections <- upset_data$connections
  set_sizes <- upset_data$set_sizes

  # Prepare data for main bar plot
  intersections$highlight <- intersections$intersection_id %in% highlight_sets
  intersections$bar_color <- ifelse(intersections$highlight,
                                      highlight_color, "gray30")

  # Create main bar plot
  p_bars <- ggplot2::ggplot(intersections,
                             ggplot2::aes(x = intersection_id, y = count)) +
    ggplot2::geom_bar(stat = "identity",
                      fill = intersections$bar_color,
                      width = 0.7) +
    ggplot2::labs(y = "Number of intersecting sequences") +
    ggplot2::theme_minimal() +
    ggplot2::theme(
      axis.title.x = ggplot2::element_blank(),
      axis.text.x = ggplot2::element_blank(),
      axis.ticks.x = ggplot2::element_blank(),
      panel.grid.major.x = ggplot2::element_blank(),
      panel.grid.minor = ggplot2::element_blank()
    )

  if (show_numbers) {
    p_bars <- p_bars +
      ggplot2::geom_text(ggplot2::aes(label = count),
                         vjust = -0.5, size = 3)
  }

  # Prepare data for connection matrix
  n_sets <- length(repertoire_ids)
  n_intersections <- nrow(connections)

  connection_df <- data.frame(
    intersection_id = rep(1:n_intersections, each = n_sets),
    set = rep(repertoire_ids, times = n_intersections),
    set_num = rep(1:n_sets, times = n_intersections),
    present = as.vector(t(connections))
  )

  # Add lines connecting dots
  line_df <- data.frame()
  for (i in 1:n_intersections) {
    sets_present <- which(connections[i, ] == 1)
    if (length(sets_present) > 1) {
      for (j in 1:(length(sets_present) - 1)) {
        line_df <- rbind(line_df, data.frame(
          intersection_id = i,
          y_start = sets_present[j],
          y_end = sets_present[j + 1]
        ))
      }
    }
  }

  # Create connection matrix plot
  p_matrix <- ggplot2::ggplot(connection_df,
                               ggplot2::aes(x = intersection_id, y = set_num)) +
    ggplot2::geom_point(data = connection_df[connection_df$present == 1, ],
                        size = 3, color = "black") +
    ggplot2::scale_y_continuous(
      breaks = 1:n_sets,
      labels = repertoire_ids,
      limits = c(0.5, n_sets + 0.5)
    ) +
    ggplot2::theme_minimal() +
    ggplot2::theme(
      axis.title = ggplot2::element_blank(),
      axis.text.x = ggplot2::element_blank(),
      axis.ticks.x = ggplot2::element_blank(),
      panel.grid.major.x = ggplot2::element_blank(),
      panel.grid.minor = ggplot2::element_blank(),
      panel.grid.major.y = ggplot2::element_line(color = "gray80")
    )

  # Add connecting lines
  if (nrow(line_df) > 0) {
    p_matrix <- p_matrix +
      ggplot2::geom_segment(data = line_df,
                            ggplot2::aes(x = intersection_id,
                                        xend = intersection_id,
                                        y = y_start, yend = y_end),
                            linewidth = 1.5, color = "black")
  }

  # Create set size barplot
  set_size_df <- data.frame(
    set = repertoire_ids,
    set_num = 1:n_sets,
    size = set_sizes[repertoire_ids]
  )

  p_sets <- ggplot2::ggplot(set_size_df,
                            ggplot2::aes(x = size, y = set_num)) +
    ggplot2::geom_bar(stat = "identity", fill = "gray30", width = 0.7) +
    ggplot2::scale_y_continuous(
      breaks = 1:n_sets,
      limits = c(0.5, n_sets + 0.5)
    ) +
    ggplot2::labs(x = "Number of sequences") +
    ggplot2::theme_minimal() +
    ggplot2::theme(
      axis.title.y = ggplot2::element_blank(),
      axis.text.y = ggplot2::element_blank(),
      axis.ticks.y = ggplot2::element_blank(),
      panel.grid.major.y = ggplot2::element_blank(),
      panel.grid.minor = ggplot2::element_blank()
    )

  # Combine plots using patchwork-style layout
  # Note: This creates a list that can be arranged with gridExtra or patchwork
  # For now, return the main plot with a note

  # Since we can't easily combine without additional dependencies,
  # return main bar plot with matrix as attribute
  p_bars$upset_matrix <- p_matrix
  p_bars$upset_sets <- p_sets

  return(p_bars)
}
