#' Highlight clones 
#' 
#' Create alluvial plots highlighting each sequence in amino acid list
#' 
#' @param clone_table A tibble of productive amino acid sequences to highlight
#' generated by LymphoSeq function cloneTrack
#' @return A list of alluvial plots highlighting a single sequence
#' @details The plot is made using the package ggplot2 and can be reformatted
#' using ggplot2 functions.  
#' @export
plotTrackSingular <- function(ctable) {
  alist <- ctable %>% pull(junction_aa) %>% unique()
  plots <- alist %>% map(~highlightPlot(.x, ctable))
  return(plots)
}

#' Highlight specific sequences
#' 
#' @describeIn plotTrackSingular Highligh a specific amino acid sequence
#' 
#' @param aseq CDR3 amino acid sequence to highlight 
#' @param ctable  tibble of productive amino acid sequences to highlight
#' generated by LymphoSeq function cloneTrack
highlightPlot <- function(aseq, ctable) {
  pal_table <- ctable %>%
            select(junction_aa) %>%
            distinct() %>%
            mutate(color = if_else(junction_aa == aseq, "#7570b3", "grey"))
  cpal <- pal_table %>% pull(color)
  names(cpal) <- pal_table %>% pull(junction_aa)
  tplot <- plotTrack(ctable) +
           scale_fill_manual(values = cpal, breaks = aseq, name = "CDR3 Sequence") +
           theme(legend.position = "bottom")
  return(tplot)
}

