#' Plot clone 
#' 
#' Creates alluvial tracking amino acid frequencies across multiple samples
#' 
#' @param clone_table A tibble of productive amino acid sequences 
#' generated by LymphoSeq function cloneTrack
#' @return An alluvial diagram tracking particular clone across samples.
#' @details The plot is made using the package ggplot2 and can be reformatted
#' using ggplot2 functions.  See examples below.
#' @export

plotTrack <- function(clone_table) {
  set.seed(12345)
  # Identify all common sequences across samples
  acommon <- clone_table %>% 
             dplyr::filter(seen >= 2) %>%
             LymphoSeq2::seqMatrix() %>%
             dplyr::select(junction_aa) %>%
             dplyr::pull(junction_aa)
  # Generate a distinct palatte for Amino acid sequences
  # Color sequences by occurence
  # Generate the alluvial plot to trace the frequency variation of top n Amino acid sequences
  clone_table <- clone_table %>% 
                  dplyr::group_by(repertoire_id) %>% 
                  dplyr::arrange(desc(duplicate_frequency)) %>% 
                  dplyr::ungroup()
  #print(sample_table)
  sankey <- ggplot2:: ggplot(clone_table, 
                             aes(x = repertoire_id, y = duplicate_frequency, stratum = junction_aa, 
                                 alluvium=junction_aa, fill=junction_aa, label=junction_aa)) + 
            ggalluvial::geom_alluvium() + 
            ggalluvial::geom_stratum(aes(y=duplicate_frequency)) + 
            ggplot2::scale_y_continuous(name = "Frequency of top CDR3 sequence") +
            ggplot2::xlab("Repertoire ID") +
            ggplot2::ylab("Frequency of CDR3 sequence") +
            ggplot2::theme_classic() +
            ggplot2::theme(legend.position = "none",
                           axis.text.x = element_text(angle = -90)) 
    
  return(sankey)
}
